name: Deploy to Fly.io

on:
  push:
    branches:
      - master  # Cambia "main" si tu rama principal se llama de otra manera

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ FlyV1 fm2_lJPECAAAAAAAB8XCxBDIFp7uK3NVyP6WI7gbnK/JwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAA0HRx8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDwOpQb3pi/5pQbVIXLJIHmsAuqOUjXVeGcOJuk+SeVDkga3YVU3UE4epyrMullZ6NaeL9gTeCGX/94lsejETqVFJUOk6X1SizgKDSTcgbS5z5n6H+IToOO9RI/FLJ86BY9VaMg5Mt8kF3+83Hnl/t8zGVhaLOLCyAuyj39SneA9V2XPH/rv4Ff7DY5KTg2SlAORgc4ATAY1HwWRgqdidWlsZGVyH6J3Zx8BxCDQjFlJxdySODLnNPEEoo0UTb8yJ+UyB+WJ1lX2d/pFpQ==,fm2_lJPETqVFJUOk6X1SizgKDSTcgbS5z5n6H+IToOO9RI/FLJ86BY9VaMg5Mt8kF3+83Hnl/t8zGVhaLOLCyAuyj39SneA9V2XPH/rv4Ff7DY5KTsQQkB90uz2friKuYToc0f56HMO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5nFsowzoyu0E4XzgAMoEkKkc4ADKBJDMQQePByvi0xOWugqIegjl2evsQgV/7o5EmwujwcfYePV6gmE6akcnMptt7MKP/ssAzvRfU= }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy
